const Images = {
  logo: require('../assets/images/logo.png'),
  home: require('../assets/images/home.png'),
  search: require('../assets/images/search.png'),
  user: require('../assets/images/user2.png'),
  more: require('../assets/images/more.png'),
  attendanceIcon: require('../assets/images/services/attendance.png'),
  regularizationIcon: require('../assets/images/services/regularization.png'),
  leaveIcon: require('../assets/images/services/leave.png'),
  letterIcon: require('../assets/images/services/letter.png'),
  myFilesIcon: require('../assets/images/services/myFiles.png'),
  supportIcon: require('../assets/images/services/support.png'),
  editProfileIcon: require('../assets/images/profile/editProfile.png'),
  notificationIcon: require('../assets/images/profile/notification.png'),
  privacyIcon: require('../assets/images/profile/privacy.png'),
  settingsIcon: require('../assets/images/profile/settings.png'),
  logoutIcon: require('../assets/images/profile/logout.png'),
  myEmployeeIcon: require('../assets/images/services/myEmployee.png'),
  holidayIcon: require('../assets/images/services/hoilday.png'),
  announcementIcon: require('../assets/images/services/announcement.png'),
  organizationIcon: require('../assets/images/services/organization.png'),
};
export default Images;
